[2025-03-13T14:24:25.657+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T14:24:25.665+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training-pipeline.feature_engineering manual__2025-03-13T14:24:21.682786+00:00 [queued]>
[2025-03-13T14:24:25.667+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training-pipeline.feature_engineering manual__2025-03-13T14:24:21.682786+00:00 [queued]>
[2025-03-13T14:24:25.668+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-13T14:24:25.671+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): feature_engineering> on 2025-03-13 14:24:21.682786+00:00
[2025-03-13T14:24:25.676+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=348) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T14:24:25.679+0000] {standard_task_runner.py:72} INFO - Started process 358 to run task
[2025-03-13T14:24:25.677+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'training-pipeline', 'feature_engineering', 'manual__2025-03-13T14:24:21.682786+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline.py', '--cfg-path', '/tmp/tmpkgeyyfm9']
[2025-03-13T14:24:25.681+0000] {standard_task_runner.py:105} INFO - Job 93: Subtask feature_engineering
[2025-03-13T14:24:25.701+0000] {task_command.py:467} INFO - Running <TaskInstance: training-pipeline.feature_engineering manual__2025-03-13T14:24:21.682786+00:00 [running]> on host 08c43b3a6abd
[2025-03-13T14:24:25.728+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='training-pipeline' AIRFLOW_CTX_TASK_ID='feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T14:24:21.682786+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T14:24:21.682786+00:00'
[2025-03-13T14:24:25.729+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T14:24:25.773+0000] {feature_engineering_step.py:78} INFO - Start features engineering 'fit_transform'.
[2025-03-13T14:24:25.801+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.802+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.802+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.802+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.802+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.803+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.803+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.803+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.target_features] = target_encoded_data

[2025-03-13T14:24:25.803+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.target_features] = target_encoded_data

[2025-03-13T14:24:25.803+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.target_features] = target_encoded_data

[2025-03-13T14:24:25.803+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.target_features] = target_encoded_data

[2025-03-13T14:24:25.804+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:92: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.target] = target_col

[2025-03-13T14:24:25.820+0000] {feature_engineering_step.py:96} INFO - Features and encoders successfully saved respectively to /opt/***/data/features_store/train.parquet and /opt/***/artifacts/encoders.joblib
[2025-03-13T14:24:25.821+0000] {feature_engineering_step.py:111} INFO - Start features engineering 'transform'.
[2025-03-13T14:24:25.897+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.898+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.898+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.898+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.899+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.899+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.899+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-13T14:24:25.900+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.target_features] = target_encoded_data

[2025-03-13T14:24:25.901+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.target_features] = target_encoded_data

[2025-03-13T14:24:25.903+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.target_features] = target_encoded_data

[2025-03-13T14:24:25.905+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.target_features] = target_encoded_data

[2025-03-13T14:24:25.906+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.target] = target_col

[2025-03-13T14:24:25.938+0000] {feature_engineering_step.py:128} INFO - Features successfully saved to /opt/***/data/features_store/test.parquet
[2025-03-13T14:24:25.943+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-13T14:24:25.947+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T14:24:25.947+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=training-pipeline, task_id=feature_engineering, run_id=manual__2025-03-13T14:24:21.682786+00:00, execution_date=20250313T142421, start_date=20250313T142425, end_date=20250313T142425
[2025-03-13T14:24:25.998+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-13T14:24:26.008+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-13T14:24:26.009+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
