[2025-03-12T13:45:31.078+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T13:45:31.090+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training-pipeline.feature_engineering manual__2025-03-12T13:45:24.607347+00:00 [queued]>
[2025-03-12T13:45:31.095+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training-pipeline.feature_engineering manual__2025-03-12T13:45:24.607347+00:00 [queued]>
[2025-03-12T13:45:31.096+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-12T13:45:31.103+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): feature_engineering> on 2025-03-12 13:45:24.607347+00:00
[2025-03-12T13:45:31.113+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T13:45:31.114+0000] {standard_task_runner.py:72} INFO - Started process 92 to run task
[2025-03-12T13:45:31.114+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'training-pipeline', 'feature_engineering', 'manual__2025-03-12T13:45:24.607347+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline.py', '--cfg-path', '/tmp/tmpprwi__um']
[2025-03-12T13:45:31.116+0000] {standard_task_runner.py:105} INFO - Job 81: Subtask feature_engineering
[2025-03-12T13:45:31.144+0000] {task_command.py:467} INFO - Running <TaskInstance: training-pipeline.feature_engineering manual__2025-03-12T13:45:24.607347+00:00 [running]> on host 3c0fa6099d7a
[2025-03-12T13:45:31.173+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='training-pipeline' AIRFLOW_CTX_TASK_ID='feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T13:45:24.607347+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T13:45:24.607347+00:00'
[2025-03-12T13:45:31.174+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T13:45:31.240+0000] {feature_engineering_step.py:78} INFO - Start features engineering 'fit_transform'.
[2025-03-12T13:45:31.272+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.273+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.273+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.273+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.274+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.274+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.274+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:88: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.274+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.target_features] = target_encoded_data

[2025-03-12T13:45:31.274+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.target_features] = target_encoded_data

[2025-03-12T13:45:31.274+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.target_features] = target_encoded_data

[2025-03-12T13:45:31.275+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.target_features] = target_encoded_data

[2025-03-12T13:45:31.275+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:92: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[feature_encoders.target] = target_col

[2025-03-12T13:45:31.293+0000] {feature_engineering_step.py:96} INFO - Features and encoders successfully saved respectively to /opt/***/data/features_store/train.parquet and /opt/***/artifacts/encoders.joblib
[2025-03-12T13:45:31.294+0000] {feature_engineering_step.py:111} INFO - Start features engineering 'transform'.
[2025-03-12T13:45:31.390+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.391+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.391+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.392+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.392+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.394+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.395+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.ordinal_features] = ordinal_encoded_data

[2025-03-12T13:45:31.395+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.target_features] = target_encoded_data

[2025-03-12T13:45:31.396+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.target_features] = target_encoded_data

[2025-03-12T13:45:31.396+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.target_features] = target_encoded_data

[2025-03-12T13:45:31.396+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.target_features] = target_encoded_data

[2025-03-12T13:45:31.397+0000] {warnings.py:112} WARNING - /opt/***/dags/steps/feature_engineering_step.py:125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_df[features_encoder.target] = target_col

[2025-03-12T13:45:31.433+0000] {feature_engineering_step.py:128} INFO - Features successfully saved to /opt/***/data/features_store/test.parquet
[2025-03-12T13:45:31.438+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T13:45:31.442+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T13:45:31.442+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=training-pipeline, task_id=feature_engineering, run_id=manual__2025-03-12T13:45:24.607347+00:00, execution_date=20250312T134524, start_date=20250312T134531, end_date=20250312T134531
[2025-03-12T13:45:31.464+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T13:45:31.474+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-12T13:45:31.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
